### ISSUE TITLE
本地运行报了个错

### ISSUE THREAD

**Issue by xlflove** [GuoQuanhao/arcface-Paddle#2]
Traceback (most recent call last):
  File "train.py", line 114, in <module>
    main(args)
  File "train.py", line 100, in main
    callback_verification(global_step, backbone)
  File "/root/autodl-tmp/arcface_autodl/utils/utils_callbacks.py", line 49, in __call__
    self.ver_test(backbone, num_update, batch_size)
  File "/root/autodl-tmp/arcface_autodl/utils/utils_callbacks.py", line 29, in ver_test
    acc1, std1, acc2, std2, xnorm, embeddings_list = verification.test(
  File "/root/miniconda3/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 315, in _decorate_function
    return func(*args, **kwargs)
  File "/root/autodl-tmp/arcface_autodl/eval/verification.py", line 278, in test
    _, _, accuracy, val, val_std, far = evaluate(embeddings, issame_list, nrof_folds=nfolds)
  File "/root/autodl-tmp/arcface_autodl/eval/verification.py", line 191, in evaluate
    val, val_std, far = calculate_val(thresholds,
  File "/root/autodl-tmp/arcface_autodl/eval/verification.py", line 151, in calculate_val
    f = interpolate.interp1d(far_train, thresholds, kind='slinear')
  File "/root/miniconda3/lib/python3.8/site-packages/scipy/interpolate/_interpolate.py", line 616, in __init__
    self._spline = make_interp_spline(xx, yy, k=order,
  File "/root/miniconda3/lib/python3.8/site-packages/scipy/interpolate/_bsplines.py", line 1293, in make_interp_spline
    raise ValueError("Expect x to not have duplicates")
ValueError: Expect x to not have duplicates

far_train 中可能存在重复的元素？

**Comment by GuoQuanhao** [comment]
建议使用AIStudio运行，这个项目比较久了，PaddlePaddle版本已更新迭代多次

**Comment by sabahmax-dev** [comment]
你好！已提交 PR #3 来修复这个问题：`far_train` 中如果存在重复元素，会导致 `scipy.interpolate.interp1d` 报错。PR 中会先对 `far_train` 去重并排序后再进行插值，从而避免这个 `ValueError`。欢迎试用～
